### ISSUE TITLE
Automatic form binding

### ISSUE THREAD

**Issue by rodryquintero** [NYTimes/backbone.stickit#141]
Why not implement a way to automatically bind form elements to model attributes, in a way similar to **Backbone.ModelBinding**.

It was so convenient to simply initialize the binding call and have every form element bound automatically using the elements "id" to match the model attribute.

Any thoughts?

**Comment by isochronous** [comment]
Sorry for the (very) delayed reply - You don't have to override render functions, you can just do something like this:

```js
// in your view prototype
initialize: function(options) {
    this.listenTo(this, 'render', this.createDefaultBindings);
}
```

Never underestimate the value of backbone events and event listeners!

**Comment by isochronous** [comment]
Oh, and one other thing - we used the Backbone.Super plugin (which gives you easy access to a super-class's implementation of a method) and we had our own custom base view type for all views in our app.  That base view class called `createDefaultBindings` on `show`, not on `render` (for a wizard, we might render 5 views at the same time, but only ever show one at a time).  Then, if any view that extended that base class needed to implement an `onShow` method, they could do so, and simply add `this._super();` to the method, and it would invoke that base class's onShow method, which would call `createDefaultBindings` in turn.

Granted, I've learned a lot about Backbone since then, and I wouldn't necessarily do it the same way now, but it worked well at the time, and it was easy for the team members who were learning JavaScript after working in nothing but C# for years to figure it out because they were used to thinking in terms of class hierarchies.
