### ISSUE TITLE
Updating collection bound to multiple selects only updates the last one

### ISSUE THREAD

**Issue by gdw2** [NYTimes/backbone.stickit#250]
I have several select widgets all bound to the same collection.  When I update the collection, only the last widget is updated.  I'm guessing that when a Backbone.Collection is bound to a select, it removes all previous refresh listeners associated with that collection.  

I found this while exercising the functionality added in: 
https://github.com/NYTimes/backbone.stickit/pull/237

**Comment by drummerboof** [comment]
I am seeing what I believe is this issue as well although I don't have multiple selects. The issue is that re-rendering breaks the collection bindings if the select is the last binding in the bindings map. I have created a [JSFiddle to show the issue here](http://jsfiddle.net/cn9nh45f/1/)

For me, I am only seeing the issue once the view has been "re-rendered". You will see on the fiddle that the select is being correctly updated when clicking the "Reset collection" button until you click the "Re-render view" button. At this point, the bindings to the collection are removed (despite stickit() being called on render).

If you move the title binding above the options binding in the view code and re-run the Fiddle, you will see that it starts working as expected.

**Comment by yousefcisco** [comment]
It seems this issue is caused by the event cleanup performed when `unstickit` is called. It's really odd because I can see the events are readded when `stickit` is called again but the callback isn't triggering properly. I'll try and look into this in more detail over the weekend

**Comment by rwhitmire** [comment]
I am also experiencing this issue. Here's a simple fiddle demonstrating the problem: http://jsfiddle.net/rwhitmire/9rtd6y07/2/

Are there any fixes/workarounds at the moment? I can try to take a look at the issue tonight if not.

**Comment by rwhitmire** [comment]
The issue was related to the collection `stickit:selectRefresh` event being triggered each time a new view referencing a single collection was rendered.

I created a new event `selectRefreshForView` to which I pass the view's `cid` and then trigger the `stickit:selectRefresh` event only if the passed `cid` matches `this.cid`

**Comment by akre54** [comment]
Worth adding as a patch? Otherwise good to know, thanks!

**Comment by rwhitmire** [comment]
I think it would be - but I'm biased since my company is now running my own forked version of stickit and I don't like that haha.

**Comment by akre54** [comment]
Feel free to open a pull. Happy to take a look at an implementation that
fixes this.

**Comment by rwhitmire** [comment]
already done: https://github.com/NYTimes/backbone.stickit/pull/280
