### ISSUE TITLE
DOM Attribute bindings set empty attributes for empty values...

### ISSUE THREAD

**Issue by mattbryson** [NYTimes/backbone.stickit#291]
Whilst this is kinds of expected, as its a refection of the data, is there any way to NOT store empty data attributes on the DOM if the model value is empty?

**Comment by akre54** [comment]
Sure -- override [`update`](https://github.com/NYTimes/backbone.stickit#update) if you're doing something custom. Anything more advanced you should create a Handler for.

We can't change it for everyone, because that would break things like inputs or class names where we *want* to use an empty string for empty values.
